### ISSUE TITLE
Настоящее энерго-сбережение

### ISSUE THREAD

**Issue by heX16** [noant/Lazurite#6]
В программе есть множество режимов энергосбережения.
На даже самый "экономный" делает синхронизацию раз в час.
Мне повезло - на моем телефоне можно запретить фоновую активность любой программы.
Но что делать другим?
Нужно добавить режим - "без синхронизации и фоновой активности".

User case:
Использую программу просто как пульт управления. Не использую "сообщения" (на телефоне и без этого слишком много месседжеров), не использую GPS.
Данные от хаба нужны только в момент когда программа непосредственно открыта. Тоесть программа запустилась, законектилась, получила данные, я с ней поработал, вышел из нее, и все. В этом случае фоновая синхронизация не нужна, это просто лишний трафик.

**Comment by noant** [comment]
Понял, это добавить будет не сложно. Думаю, в следующем релизе уже будет.

**Comment by noant** [comment]
Выложил версию, в который будет режим энергосбережения "Без фоновой активности".
Сейчас можно найти в релизах, на Play Market будет доступна в ближайшие часы.
